export enum SignalType {
  PUBLICKEYS = "public-keys:",
  FILE_MESSAGE = "file-message",
  ENCRYPTED_MESSAGE = "encrypted-message",
  SERVERLIMIT = "SERVERLIMIT:",
  SERVERMESSAGE = "SERVERMESSAGE:",
  NAMEEXISTSERR = "NAMEEXISTSERR:", 
  INVALIDNAMELENGTH = "INVALIDNAMELENGTH:",
  INVALIDNAME = "INVALIDNAME:",
}