export enum SignalType {
  PUBLICKEYS = "public-keys",
  FILE_MESSAGE = "file-message",
  FILE_MESSAGE_CHUNK = "file-message-chunk",
  ENCRYPTED_MESSAGE = "encrypted-message",
  USER_DISCONNECT = "user-disconnect",
  SERVERLIMIT = "server-limit",
  SERVERMESSAGE = "server-message",
  NAMEEXISTSERROR = "name-exists-error", 
  INVALIDNAMELENGTH = "invalid-name-length",
  INVALIDNAME = "invalid-name",
  SERVER_PASSWORD_ENCRYPTED = "server-password-encrypted",
  SERVER_PUBLIC_KEY = "server-public-key",
  LOGIN_INFO = "login-info",
  ACCOUNT_SIGN_IN = "account-sign-in",
  ACCOUNT_SIGN_UP = "account-sign-up",
  IN_ACCOUNT = "in-account",
  DELETE_MESSAGE = "delete-message",
  EDIT_MESSAGE = "edit-message",
  AUTH_ERROR = "AUTH_ERROR",
  AUTH_SUCCESS = "AUTH_SUCCESS",
}